version: '3.8'

services:
  # 后端服务
  backend:
    # 假设你有后端的 Dockerfile 或镜像
    # build: ./backend
    # 或者使用现有镜像
    image: your-backend-image:latest
    container_name: bodian-backend
    ports:
      - "5000:5000"  # 暴露后端端口，便于直接访问调试
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - bodian-network
    restart: unless-stopped

  # 前端服务 (Nginx + 静态文件)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: production
    container_name: bodian-frontend
    ports:
      - "80:80"     # 主要访问端口
      - "8088:80"   # 备用端口
    environment:
      # 配置后端地址 - 根据部署方式选择
      # 选项1: Docker 内部网络 (推荐)
      - BACKEND_HOST=backend:5000
      # 选项2: 公网 IP (如果后端独立部署)
      # - BACKEND_HOST=47.101.39.246:5000
      # 选项3: 本地开发
      # - BACKEND_HOST=localhost:5000
    depends_on:
      - backend
    networks:
      - bodian-network
    restart: unless-stopped

networks:
  bodian-network:
    driver: bridge

# 可选：添加数据卷
volumes:
  backend-data:
    driver: local