services:
  redis:
    image: redis:7-alpine
    container_name: prod_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_prod_data:/data
    networks:
      - prod_network
    restart: always

  backend-prod:
    image: crpi-2l13lq8qqggkzp5n.cn-shanghai.personal.cr.aliyuncs.com/develop_daily/bodian_backend:0.2
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env.prod
    networks:
      - prod_network
    depends_on:
      - redis
    restart: always
    # 简化的健康检查 - 只检查端口是否开放
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 5000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend-prod:
    image: crpi-2l13lq8qqggkzp5n.cn-shanghai.personal.cr.aliyuncs.com/develop_daily/bodian_frontend:0.3
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_HOST=backend:5000
    networks:
      - prod_network
    depends_on:
      backend-prod:
        condition: service_healthy
    restart: always

networks:
  prod_network:
    driver: bridge

volumes:
  redis_prod_data:
    driver: local